language: go

notifications:
  email: false

go:
  - 1.5

install:
  - go get github.com/asaskevich/EventBus
  - go get github.com/ugorji/go/codec
  - go get github.com/zeromq/gomq

script:
  - go test -v .
